version: '3.9'

networks:
  mynet:

services:
  flask1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask1
    networks:
      - mynet

  flask2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask2
    networks:
      - mynet

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8181:81"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask1
      - flask2
    networks:
      - mynet
