version: '3'

services:
  backend:
    image: alpine
    container_name: backend
    command: sh -c "apk add curl && sleep 3600"
    networks:
      - private-net

  db:
    image: redis:latest
    container_name: redis-db
    networks:
      - private-net

networks:
  private-net:
    driver: bridge
