version: '3.8'
services:
  app:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  tests:
    build: ./app
    volumes:
      - ./app:/app
    entrypoint: ["pytest", "--maxfail=1", "--disable-warnings"]
