version: '3.8'
services:
  app:
    build: ./app
    image: myapp:latest

  nginx:
    image: nginx:alpine
    ports:
      - "91:91"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
