version: '3.8'

services:
  db:
    image: mariadb:11
    container_name: nextcloud_db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_PASSWORD: nextcloudpass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  redis:
    image: redis:7
    container_name: nextcloud_redis
    restart: always

  app:
    image: nextcloud:27
    container_name: nextcloud_app
    restart: always
    ports:
      - "1111:80"
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      MYSQL_PASSWORD: nextcloudpass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
      REDIS_HOST: redis
    depends_on:
      - db
      - redis

volumes:
  db_data:
  nextcloud_data:
