version: '3.8'

services:
  nodejs:
    image: node:14
    container_name: nodejs-app
    working_dir: /app
    volumes:
      - ./nodejs-app:/app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mariadb
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydb1
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb-containers
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: mydb1
    ports:
      - "3000:3000"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
