version: '3.8'

services:
  web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_app:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    container_name: celery_worker
    command: celery -A django_project worker --loglevel=info
    volumes:
      - ./django_app:/app
    depends_on:
      - redis
      - web

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
